

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.JFrame;
/**
 *
 * @author uday0
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
	initComponents();
	Panel2.setBackground(new Color(0,0,0,0));
	Panel1.setBackground(new Color(0,0,0,0));
		BadaPanel.setBackground(new Color(0,0,0,0));
			jPanel11.setBackground(new Color(0,0,0,0));
			jPanel12.setBackground(new Color(0,0,0,0));
			jPanel9.setBackground(new Color(0,0,0,0));
			jPanel13.setBackground(new Color(0,0,0,0));
		// Set the background color to a non-transparent color


		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel2 = new javax.swing.JPanel();
        BadaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new RoundedPanel(20, new Color(201, 0, 102, 100));
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PatientButton = new javax.swing.JButton();
        jPanel11 = new RoundedPanel(20, new Color(201, 0, 102, 100));
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MedicalButton1 = new javax.swing.JButton();
        jPanel12 = new RoundedPanel(20, new Color(201, 0, 102, 100));
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        MedicalButton2 = new javax.swing.JButton();
        jPanel13 = new RoundedPanel(20, new Color(201, 0, 102, 100));
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MedicalButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(870, 470));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 0, 0));
        kGradientPanel1.setkGradientFocus(400);
        kGradientPanel1.setkStartColor(new java.awt.Color(153, 0, 51));
        kGradientPanel1.setLayout(new java.awt.BorderLayout());

        Panel1.setBackground(new java.awt.Color(204, 0, 102));
        Panel1.setOpaque(false);
        Panel1.setPreferredSize(new java.awt.Dimension(398, 80));
        Panel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Management System");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weighty = 10.0;
        Panel1.add(jLabel1, gridBagConstraints);

        kGradientPanel1.add(Panel1, java.awt.BorderLayout.PAGE_START);

        Panel2.setBackground(new java.awt.Color(204, 0, 102));
        Panel2.setOpaque(false);
        Panel2.setLayout(new java.awt.GridBagLayout());

        BadaPanel.setBackground(new java.awt.Color(255, 51, 102));
        BadaPanel.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Explore ");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 21));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("_______________");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 21));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("     _______________");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 21));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        jPanel9.setBackground(new java.awt.Color(0, 255, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel9.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Patient");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel9.add(jLabel5);
        jLabel5.setBounds(12, 15, 159, 21);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/patient.png"))); // NOI18N
        jPanel9.add(jLabel10);
        jLabel10.setBounds(138, 37, 50, 50);

        PatientButton.setBackground(new java.awt.Color(165, 0, 0));
        PatientButton.setBorder(null);
        PatientButton.setBorderPainted(false);
        PatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonActionPerformed(evt);
            }
        });
        jPanel9.add(PatientButton);
        PatientButton.setBounds(-10, -10, 220, 120);

        jPanel7.add(jPanel9);

        jPanel11.setBackground(new java.awt.Color(0, 255, 102));
        jPanel11.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel11.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hospital");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel11.add(jLabel13);
        jLabel13.setBounds(12, 15, 159, 21);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hosp.png"))); // NOI18N
        jPanel11.add(jLabel14);
        jLabel14.setBounds(138, 37, 50, 50);

        MedicalButton1.setBackground(new java.awt.Color(165, 0, 0));
        MedicalButton1.setBorder(null);
        MedicalButton1.setBorderPainted(false);
        MedicalButton1.setFocusPainted(false);
        MedicalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalButton1ActionPerformed(evt);
            }
        });
        jPanel11.add(MedicalButton1);
        MedicalButton1.setBounds(-10, -10, 220, 120);

        jPanel7.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(0, 255, 102));
        jPanel12.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel12.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Medical Rec");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel12.add(jLabel15);
        jLabel15.setBounds(12, 15, 159, 21);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medrec.png"))); // NOI18N
        jPanel12.add(jLabel16);
        jLabel16.setBounds(138, 37, 50, 50);

        MedicalButton2.setBackground(new java.awt.Color(165, 0, 0));
        MedicalButton2.setBorder(null);
        MedicalButton2.setBorderPainted(false);
        MedicalButton2.setFocusPainted(false);
        MedicalButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(MedicalButton2);
        MedicalButton2.setBounds(-10, -10, 220, 120);

        jPanel7.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(0, 255, 102));
        jPanel13.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel13.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Doctor");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 21));
        jPanel13.add(jLabel17);
        jLabel17.setBounds(12, 15, 159, 21);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital.png"))); // NOI18N
        jPanel13.add(jLabel18);
        jLabel18.setBounds(138, 37, 42, 50);

        MedicalButton3.setBackground(new java.awt.Color(165, 0, 0));
        MedicalButton3.setBorder(null);
        MedicalButton3.setBorderPainted(false);
        MedicalButton3.setFocusPainted(false);
        MedicalButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalButton3ActionPerformed(evt);
            }
        });
        jPanel13.add(MedicalButton3);
        MedicalButton3.setBounds(-10, -10, 220, 120);

        jPanel7.add(jPanel13);

        javax.swing.GroupLayout BadaPanelLayout = new javax.swing.GroupLayout(BadaPanel);
        BadaPanel.setLayout(BadaPanelLayout);
        BadaPanelLayout.setHorizontalGroup(
            BadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BadaPanelLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        BadaPanelLayout.setVerticalGroup(
            BadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BadaPanelLayout.createSequentialGroup()
                .addGroup(BadaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel2.add(BadaPanel, new java.awt.GridBagConstraints());

        kGradientPanel1.add(Panel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(632, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MedicalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalButton1ActionPerformed
       
         HOSPITAL hospital=new HOSPITAL();
        setVisible(false);
        hospital.setVisible(true);  

    }//GEN-LAST:event_MedicalButton1ActionPerformed

    private void MedicalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalButton2ActionPerformed
 MEDICALRECORDS medicalrecords=new MEDICALRECORDS();
        setVisible(false);
        medicalrecords.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalButton2ActionPerformed

    private void MedicalButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalButton3ActionPerformed
 DOCTOR doctor=new DOCTOR();
        setVisible(false);
        doctor.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalButton3ActionPerformed

    private void PatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonActionPerformed
 PATIENT patient=new PATIENT();
        setVisible(false);
        patient.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PatientButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new HomePage().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BadaPanel;
    private javax.swing.JButton MedicalButton1;
    private javax.swing.JButton MedicalButton2;
    private javax.swing.JButton MedicalButton3;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JButton PatientButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables

 



    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());

        }
    }

}
